before:
  hooks:
    - go get github.com/rakyll/statik
    - $GOPATH/bin/statik -src=./server/static -include='*.html'
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
