debug = true

[agent]
listen_address = "0.0.0.0:3333"
poll_interval = 1

[server]
dsn = "kimo:123@(mysql:3306)/information_schema"
listen_address = "0.0.0.0:3322"
poll_interval = 3
agent_port = 3333
tcpproxy_mgmt_address = "tcpproxy:3307"
