debug: true

agent:
    listen_address: "0.0.0.0:3333"
    poll_interval: "10s"

server:
    listen_address: "0.0.0.0:3322"
    poll_interval: "12s"
    mysql:
        dsn: "kimo:123@(mysql:3306)/information_schema"
    agent:
        # kimo-agent listens this port.
        port: 3333
    tcpproxy:
        mgmt_address: "tcpproxy:3307"
    metric:
        # If one of these pattern match whole cmdline will be exposed as , otherwise it will be truncated.
        cmdline_patterns:
            - "mysql*"
