debug = true
[agent]
listen_address = "0.0.0.0:3333"
[server]
dsn = "kimo:123@(mysql:3306)/information_schema"
listen_address = "0.0.0.0:3322"
poll_duration = 10
agent_port = 3333
tcpproxy_mgmt_address = "tcpproxy:3307"
agent_connect_timeout = 1
agent_read_timeout = 4
tcpproxy_connect_timeout = 1
tcpproxy_read_timeout = 2
