version: '3.2'
services:
  mysql:
    image: kimo/mysql
    container_name: mysql
    build:
      dockerfile: Dockerfile-mysql
      context: .
    ports:
      - "3306:3306"
  tcpproxy:
    image: kimo/tcpproxy
    container_name: tcpproxy
    build:
      dockerfile: Dockerfile-tcpproxy
      context: .
    depends_on:
      - mysql
    ports:
      - "3307:3307"
    tty: true
    privileged: true
  kimo:
    image: kimo
    container_name: kimo
    build:
      dockerfile: Dockerfile-kimo
      context: .
    depends_on:
      - mysql
    tty: true
  kimo-agent:
    image: kimo-agent
    build:
      dockerfile: Dockerfile-kimo-agent
      context: .
    ports:
      - "3333"
    depends_on:
      - tcpproxy
    tty: true
  kimo-server:
    image: kimo-server
    container_name: kimo-server
    entrypoint: kimo --debug server
    ports:
      - "3322:3322"
    build:
      dockerfile: Dockerfile-kimo
      context: .
    tty: true
