FROM golang:1.13

RUN apt-get update && apt-get -y install default-mysql-client

RUN mkdir /go/src/kimo
COPY . /go/src/kimo

RUN go get github.com/rakyll/statik
RUN cd /go/src/kimo && statik -src=./server/static -include='*.html'
RUN cd /go/src/kimo && go install

ADD config.toml /etc/kimo.toml