version: '3.9'
services:
  mysql:
    image: kimo/mysql
    container_name: kimo-mysql
    build:
      dockerfile: Dockerfile-mysql
      context: .
    ports:
      - "3306:3306"
  tcpproxy:
    image: cenkalti/tcpproxy
    container_name: kimo-tcpproxy
    depends_on:
      - mysql
    ports:
      - "3307:3307"
    tty: true
    privileged: true
    command:
      - "-m"
      - "0.0.0.0:3307"
      - "0.0.0.0:3306"
      - "mysql:3306"
  kimo:
    image: kimo
    container_name: kimo
    build:
      dockerfile: Dockerfile-kimo
      context: .
    depends_on:
      - mysql
    tty: true
  kimo-agent:
    image: kimo-agent
    build:
      dockerfile: Dockerfile-kimo-agent
      context: .
    ports:
      - "3333"
    depends_on:
      - tcpproxy
    tty: true
    scale: 3
  kimo-server:
    image: kimo
    container_name: kimo-server
    entrypoint: kimo --debug server
    ports:
      - "3322:3322"
    build:
      dockerfile: Dockerfile-kimo
      context: .
    tty: true
